# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ιστιοπλοϊκά Μαθηματικά
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Ενας χώρος για μαθηματικά ιστιοπλοΐα και άλλα πολλά!!
baseurl: "/sailing-maths" # the subpath of your site, e.g. /blog
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

permalink: topics/:title/
